### ISSUE TITLE
Permettre la configuration du timeout

### ISSUE THREAD

**Issue by guillaumecardon** [sabinus52/TuyaCloudApi#3]
Hello !

J'ai eu 2 ou 3 fois une erreur de timeout dans un appel Curl :
cURL error 28: Operation timed out after 2000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 28: Operation timed out after 2000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at D:\\laragon\\www\\vulcania\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:200)
[stacktrace]

Peut-être n'est-ce pas suffisant, mais je pense que l'option peut être définie dans la fonction _request
```
$response = $this->session->getClient()->post(new Uri('/homeassistant/skill'), array(
	'timeout' => 5000,
	'json' => array(
		'header' => array(
			'name'           => $name,
			'namespace'      => $namespace,
			'payloadVersion' => 1,
		),
		'payload' => $payload + array(
			'accessToken'    => $token,
		),
	),
));
```

S'il y'a moyen de définir ce timeout dans un endroit un peu plus propre que directement dans la fonction privée..

**Comment by sabinus52** [comment]
Bonjour,

Je pense qu'il faudrait vérifier la configuration réseau et surtout si les serveurs DNS répondent bien.
J'ai eu des retours à ce sujet avec le plugin Jeedom. Depuis que ces personnes ont modifié leur configuration réseau, ils n'ont plus eu le problème. 
Le timeout par défaut est largement suffisant pour les besoins de la domotique. Il est préférable d'avoir une latence au minimum sinon Madame ne sera pas très contente si par exemple une lampe met 30 sec pour s'allumer.
