### ISSUE TITLE
Pb de Sessions

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/TuyaCloudApi#4]
Salut Sabinus ! 
L'impression que personne n'a fait l'effort de venir t'en informer ici : 
Sur l'utilisation Du Plugin (tout marchait Super jusque là) 
Nous avons assez souvent l'erreur : 
« Erreur de connexion au cloud Tuya : you cannot auth exceed once in 60 seconds » 
Ce qui bloque l'action ... 
Qq un a ouvert un sujet dans la communauté Jeedom : 
Chez moi le pb date de 2 jrs , et est aléatoire (exemple mes volets fonctionnent tjrs bien le matin, et le soir tjrs le message plus haut sur 2 des 4 volets ... )
Je voulais t'en informer ici (je sais que tu lis ici)
Merci à toi d'une réponse . 

Bonne Journée, Bon "deconfinement, bon week end
Hervé

**Comment by HerveKr** [comment]
Je vois que je ne t'ai pas donné l'adresse du sujet : https://community.jeedom.com/t/plugin-smartlife/43591

**Comment by guillaumecardon** [comment]
Tuya a rajouté une restriction qui comme son message l'indique : On ne peut pas s'authentifier plusieurs fois en moins de 60 sec"

Je pense que pour résoudre le souci, il suffirait de pouvoir réutiliser l'objet créé lors d'un "new Session()"
Dans l'exemple sur le Git, il n'y a pas de souci vu qu'on réutilise la variable $api

```
$session = new Session($argv[1], $argv[2], '33', Platform::SMART_LIFE, 5.0);

// Initialize object API
$api = new TuyaCloudApi($session);
```
Le problème que les gens rencontrent (dont moi 😃 ) c'est de faire plusieurs fois "new Session()" en moins de 60 secondes.

J'ai donc tenté de stocker cet objet dans une session php pour pouvoir le réutiliser, mais je me heurte à l'erreur PHP : "Serialization of 'Closure' is not allowed"
Je pense que la façon dont est faite la classe (ou les fonctions internes) ne permet pas la sérialisation de l'objet pour le stocker.
J'en suis à chercher du côté des bibliothèques "SuperClosure" pour essayer d'encapsuler tout ça, mais ça commence à faire usine à gaz 😋 

Dans tous les cas le souci n'est pas dû à la bibliothèque de Sabinus mais bien à une nouvelle contrainte côté Tuya.

**Comment by HerveKr** [comment]
Merci de ton "explication" ! J'avoue que je ne suis pas de niveau , là . 
Suis entierement d'accord que c'est une contrainte ajoutée auj. par Tuya . 
Mais je pense qu'elle doit aussi leur poser pb ... Sans doute l'ont ils mise en place suite au pb Aws Amazon ... 
Sans etre technique , une des questions est : vont ils laisser cette contrainte .

**Comment by HerveKr** [comment]
Nb.: Désolé si je n'ai pas posté au bon endroit . L'autre fil semble "bien parti" .

**Comment by sabinus52** [comment]
Le problème vient bien de la nouvelle restriction de Tuya.
J'ai fait aussi une réponse dans le forum Jeedom cité plus haut
Je ferme donc cette issue.
